### ISSUE TITLE
Configuring printout

### ISSUE THREAD

**Issue by pmosthus** [potentialventures/cocotb#240]
Hello,

Discovered this awesome stuff some weeks ago! GREAT work!!!! :-).

I have just started to test out cocotb, and I'm wondering if its possible to reduce the length of the printouts? I.e. this is printed out, but I'm only interested in the simulation time, severity, maybe the test name, and the actual printed info from the test:
`20.00ns INFO     cocotb.SevenSegmentDisplay         ..nSegmentDisplay.py:15   in my_first_test                   Running test!`
It doesn't display very well on my not so wide monitor. Is it possible to configure the printout? I haven't found anything about that in the docs..

Best regards,
Per Magnus

**Comment by leftink** [comment]
@pmosthus Once #474 is pulled in, you will be able to set COCOTB_REDUCED_LOG_FMT environment variable and it will reduce to SimTime, Severity and Data only
