### ISSUE TITLE
FLI sim_end() always closes the GUI

### ISSUE THREAD

**Issue by leftink** [potentialventures/cocotb#252]
When using the FLI interface with QUESTA, if the simulation is launched with a GUI, the GUI is always closed at the end of the simulation.  It doesn't matter what other commands are given to keep it open.

It appears to be the functionality of mti_Quit() that causes this problem.  I updated the sim_end() as follows and everything works as expected.

void FliImpl::sim_end(void)
{
   char buffer[5];

   sprint(buffer, "stop");
   mti_Cmd(buffer);
}

**Comment by chiggs** [comment]
@leftink does the change you've suggested also work for command-line only simulations?

**Comment by leftink** [comment]
Yes, when I ran without the GUI, everything ended as expected.
