### ISSUE TITLE
Split regression tests out from examples

### ISSUE THREAD

**Issue by chiggs** [potentialventures/cocotb#258]
Cocotb currently has a mixture of examples and functionality tests all under `examples/*`

Propose changing the directory structure to introduce `tests` at the toplevel for all regression tests and reduce examples to a small number of (well documented) examples.

**Comment by stuarthodgson** [comment]
Agreed. Www should also where possible have a test_xxxx where xxxx is a bug number. Not all bugs will have tests but those tar do should relate back.

**Comment by saturn77** [comment]
I have been working on a whitepaper that explains how to use coco_tb with a simple digital IIR filter that I could share.

**Comment by chiggs** [comment]
@saturn77 that would be great - documented examples are always helpful!
