### ISSUE TITLE
FLI Signal Handle Initialise not properly using variable m_type

### ISSUE THREAD

**Issue by leftink** [potentialventures/cocotb#261]
m_type is a string, but this function is setting it to an enum value.

Further it is overridden and not currently causing problems because the super class is called at the end of the initialise function which sets the m_type to a valid string.

**Comment by stuarthodgson** [comment]
m_type at the Fli level has been changed to m_fli_type and used to store the type of object to reduced calls on the fast path for obtaining value of a signal
