### ISSUE TITLE
getvalue() in handle.py should configure the returned Binary value

### ISSUE THREAD

**Issue by leftink** [potentialventures/cocotb#269]
When getting a value from a handle a "BinaryValue()" object is created.  In my case, I tried to slice that value to get the upper bits, but the call failed because the returned value is not configured.

I believe at a minimum, the Handle should set the number of bits, but ideally it would just configure everything the BinaryValue() object needs before returning it.

**Comment by chiggs** [comment]
see also #134 which has a number of pending improvements for BinaryValue / Handle
