### ISSUE TITLE
Makefile with Riviera-Pro 2015.10

### ISSUE THREAD

**Issue by saturn77** [potentialventures/cocotb#341]
Hello All;   I have cocotb running fine with "make" for all the examples, but not when I run "make SIM=aldec" and the message that I get is : 

dirname: missing operand
Try 'dirname --help' for more information.
/home/james/public_sw/cocotb/makefiles/simulators/Makefile.aldec:96: *** "Directory containing Riviera-Pro binaries must be included in system path".  Stop.

However, in my .bashrc file I have the path including the Riviera-Pro bin directory. 

Any suggestion on how to get this to work is much appreciated. -James

**Comment by chiggs** [comment]
@saturn77 the Makefile calls `which vsim` to check where the Aldec simulator is installed.  What happens if you run the command, is it found?

Can you list the contents of the `$riviera/bin` directory.  I haven't installed 2015.10 yet so perhaps they've changed the installation layout in the new release.

Technically we should use `which riviera` anyway since vsim is just an alias to make the Aldec tool appear more like Modelsim.

**Comment by saturn77** [comment]
So when I call "which vsim" and "which riviera" I get the following results.....

![selection_394](https://cloud.githubusercontent.com/assets/5698048/11278170/bc8614f8-8eb7-11e5-8d86-39495b494bc6.png)

The contents of the /bin directory are shown here: 

![selection_393](https://cloud.githubusercontent.com/assets/5698048/11278127/8d623922-8eb7-11e5-83ba-1bd5de15f867.png)

**Comment by saturn77** [comment]
Chris, any suggestions to make changes to  
/cocotb/makefiles/simulators/Makefile.aldec file ? 

Thanks, James

**Comment by chiggs** [comment]
@saturn77 one thing you could do is comment out line 93, and set the environment variable `ALDEC_BIN_DIR=/home/james/riviera2015.10/bin/Linux64`, which should workaround this.

Also if you could post the shell you're using that would be helpful, in addition to the output of the following:

```
dirname `which riviera`
```

**Comment by saturn77** [comment]
When running dirname which riviera or dirname 'which riviera' I get the following, and I'm running bash shell.

![selection_399](https://cloud.githubusercontent.com/assets/5698048/11302193/f548c008-8f69-11e5-82e4-bb79e807b952.png)

**Comment by chiggs** [comment]
Note the backticks rather than single quotes, which instructs bash to run the command in ticks first and then use the output as the argument to dirname.

**Comment by saturn77** [comment]
Sorry about that, yes, it seems to be pointing correctly. 

![selection_400](https://cloud.githubusercontent.com/assets/5698048/11303063/e0504cf2-8f6e-11e5-9e66-7be96cd3e737.png)

**Comment by stuarthodgson** [comment]
closing as no update for 3 months
