### ISSUE TITLE
Call to "hasattr" generate log warning if attribute doesn't exist

### ISSUE THREAD

**Issue by Martoni** [potentialventures/cocotb#344]
In avalon driver (cocotb/drivers/avalon.py), there is some call to "hasattr()"  to know if an optional signal exists.

But if doesn't exist, a warning message is generated :  
```
Failed to find a hdl named %s via any registered implementation
```
This warning is generated in C function gpi_get_handle_by_name() in lib/gpi/GpiCommon.cpp file. Can we change it to not generate warning when hasattr() is called ?

**Comment by stuarthodgson** [comment]
@Martoni , There is no way for the C++ code to know that the call has come from hasattr. We could remove the the warning all together and leave to the Python to handle.

**Comment by Martoni** [comment]
@stuarthodgson, that should be better to remove it no ? because it's not really a warning in that case.

**Comment by Martoni** [comment]
I suggest to transform "LOG_WARN" in "LOG_DEBUG" : https://github.com/potentialventures/cocotb/pull/345
