### ISSUE TITLE
Test Design Avalon module fails compilation for Questa

### ISSUE THREAD

**Issue by leftink** [potentialventures/cocotb#352]
tests/deigns/avalon_module/burst_read_master.v does not build for Questa.

Questa doesn't seem to like the fact that the registers "buf_out, buf_empty, and fifo_counter" were being used in an assignment statement before being declared.

Just need to move the declarations to be before the "assign" statements.

**Comment by chiggs** [comment]
@leftink can we close this now?

**Comment by leftink** [comment]
@chiggs Closing
