### ISSUE TITLE
Need to update some of the test designs to support Questa

### ISSUE THREAD

**Issue by leftink** [potentialventures/cocotb#355]
In "tests/designs/uart2bus/Makefile", need to add support for Questa.  Should match the "modelsim" setting.

In "tests/designs/viterbi_decoder_axi4s/Makefile", need to add support for Questa.  Should match the "modelsim" setting.

**Comment by stuarthodgson** [comment]
closing as no fixed with new method of selecting valid simulation based on TOPLEVEL_LANG in the simulator makefiles
