### ISSUE TITLE
In Handle.py, recommend moving __len__() function to the SimBaseHandle class

### ISSUE THREAD

**Issue by leftink** [potentialventures/cocotb#371]
Currently, only "NonConstantObject" handles support the __len__() function.  This means in tests have to be careful of the handle type before invoking the len(handle) function.  This function will have the same implementation for all handle types so if we just move to the SimBaseHandle class, it will at least not throw an exception if someone calls len() on a handle.  The GPI interface already supports this for all handles and defaults returning 0, so it will not crash even if the capability for particular handle types is not supported by the different interfaces.

**Comment by stuarthodgson** [comment]
@leftink makes sense

**Comment by leftink** [comment]
Fixed in latest.  Closing.
