### ISSUE TITLE
Questa Makefile references vhpi instead of fli for the GPI_IMPL

### ISSUE THREAD

**Issue by leftink** [potentialventures/cocotb#372]
Need to update questa makefile to use fli and not vhpi for the GPI_IMPL.  Will need to make sure all makefiles are updated accordingly.

@chiggs and @stuarthodgson 
I am thinking that perhaps the GPI_IMPL and GPI_EXTRA variables should be removed from the makefiles as the information can be retrieved by other means.  In each simulator makefile, there is a variable for VERILOG_SOURCES and VHDL_SOURCES.  These can be used to determine which GPI implementations need to be support without forcing the "testcase" or "design" makefiles to determine if vhpi or fli or vpi should be used.  Further, TOPLEVEL_LANG can be used to distinguish which library is equivalent to GPI_IMPL and which library is equivalent to GPI_EXTRA.  Thoughts?

**Comment by stuarthodgson** [comment]
@leftink see #232 Been outstanding for a while.
