### ISSUE TITLE
Linux Mint 18 + Riviera Issues

### ISSUE THREAD

**Issue by saturn77** [potentialventures/cocotb#492]
I  recently did a new build with Linux Mint Cinammon 18 and installed cocotb. 

Running tests with iverilog worked fine. However, when running the adder test with "make SIM=aldec" I get the following errors, where the "dlopen" fails to open. 

Wondering if anyone has a good idea on the most effective way to resolve this. 

Additionally, I do have GLIBCXX_3.4.21 installed. 

Thanks. James

KERNEL: PLI/VHPI kernel's engine initialization done.
PLI: Loading library 'libvpi.so'
PLI: Function "dlopen" failed with error "/home/james/Aldec/Riviera-PRO-2016.06-x64/bin/Linux64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/james/repos/cocotb/build/libs/x86_64/libvpi.so)" when attempting to open "libvpi.so" library.
PLI:  Cannot load the "libvpi.so" library. The library does not exist or is corrupted.

**Comment by jeremyherbert** [comment]
Hi Saturn,

I'm not a Riviera user, but is Linux Mint 18 a supported platform? It looks like Riviera was compiled with a different version of glibc++ than the cocotb PLI module.

**Comment by saturn77** [comment]
Jeremy, 
Yes, Linux Mint 18 is essentially Ubuntu 16.04 Xenial. It should be supported. The Riviera-Pro version that I am using is 2016.06 x 64, this is the latest version from Aldec. I could try 2016.02 or a previous version. But it does look like an incompatibility. 
Not sure how to fix this, kind of frustrating. Perhaps a soft link somewhere is needed. 
James

**Comment by petspats** [comment]
Hey,
I think i had same issue on Ubuntu 16.
Try this:
`ln -s /usr/lib/x86_64-linux-gnu/libstdc++.so.6  /home/james/Aldec/Riviera-PRO-2016.06-x64/bin/Linux64/libstdc++.so.6`

**Comment by stuarthodgson** [comment]
Old I know but this is due to the sim vendors insisting on shipping ancient versions of tools with their tools. Also just using their tools is also not a solution that solves all the problems, I do a lot of cosimulation and need a more up to date compiler than the tools provide.
