### ISSUE TITLE
DUT input has the same name as python keyword - in

### ISSUE THREAD

**Issue by OrionBytes** [potentialventures/cocotb#514]
Is there a way in cocotb to work with RTL where port names are similar to Python keywords.
F.e.
dut.in  -- SyntaxError: invalid syntax

**Comment by leftink** [comment]
@OrionBytes I would recommend changing the name, but if that is totally out of the question, I believe the following will do what you want:
```python
hdl_in = getattr(dut, 'in')
```

**Comment by OrionBytes** [comment]
Thank you! Perfect way when it's important to save the bad name.
