### ISSUE TITLE
https://gitter.im/cocotb

### ISSUE THREAD

**Issue by OrionBytes** [potentialventures/cocotb#529]
I create https://gitter.im/cocotb
to help more people with Cocotb usage and to get help too :)
If @chiggs or anyone from potential ventures will want to create official channel - I will free my.

**Comment by OrionBytes** [comment]
@mciepluc @luked80 @leftink and other members without public email on Github - I was unable to invite you.

**Comment by OrionBytes** [comment]
@chiggs I add you as administrator if case you prefer to use Gitter too

**Comment by juliusbaxter** [comment]
Nice one.

I think it's also worth mentioning that the FOSSi Foundation's LibreCores recently set up a cocotb mailing list: https://lists.librecores.org/listinfo/cocotb

Feel free to sign up and start blasting away there, too.

**Comment by TC01** [comment]
It would be nice to add a link to this channel from the README, otherwise people will only stumble across it by looking at the issue tracker.

**Comment by eric-wieser** [comment]
@OrionBytes, can you add @imphil as an administrator too?
