### ISSUE TITLE
hexdiff memory overflow on large transactions

### ISSUE THREAD

**Issue by oligu** [potentialventures/cocotb#542]
Around line 250 in utils.py there is a double for-loop traversing two strings  and storing some data in an array:
```python
for j in range(len(y)):
        for i in range(len(x)):
            d[i, j] = ...
```
This is used by the scoreaboard to compare the expected and the received transaction.
In my implementation the length of each of these strings is more than 5000 elements.
This results in an array d[] which is too big to handle and results in a crash of the simulator (ModelSim).

**Comment by stuarthodgson** [comment]
This is a really a problem with Modelsim (32 bit by any chance?).

**Comment by oligu** [comment]
ModelSim 32-bit is involved, yes. Have to check if it works with another simulator.
