### ISSUE TITLE
Time in iverilog is measured in seconds

### ISSUE THREAD

**Issue by andresdemski** [potentialventures/cocotb#558]
Hello,
I'm starting to use cocotb with iverilog and i found that the arguments of Clock and Timer should be in ps but they are interpreted as seconds.
```
def test (dut):
    cocotb.fork(Clock(dut.clk,100).start())
    yield Timer(100000)
```  
![image](https://user-images.githubusercontent.com/5638582/28196518-9387d370-6827-11e7-8784-2ded77d91ad2.png)

When i tried to use `units`, it raised the following exception:
![image](https://user-images.githubusercontent.com/5638582/28196819-6d6f2eb6-6829-11e7-8dcc-abe7371205b3.png)

**Comment by ajeshp** [comment]
I assume you don't have a `timescale directive declared in dut.
`timescale <reference_time_unit>/<time_resolution>, I usually use `timescale 1ns/1ps

If you don't have it, then adding it should solve your issue.

**Comment by andresdemski** [comment]
It works. Thank you
