### ISSUE TITLE
injection 'x'  in input port

### ISSUE THREAD

**Issue by kirknodeng** [potentialventures/cocotb#567]
Can I inject to input port ? 
dut.port_a = 'x' or 'X'

**Comment by AlexanderSpirin** [comment]
``` python
self.bus.tlast.value = BinaryValue('X')
```

**Comment by kirknodeng** [comment]
When I used BusDriver, it can be inject 'x'. 

But, When I directly used  in @cocotb.test (like dut.port_a = BinaryValue('X')). 
It works floating('z')
