### ISSUE TITLE
iteritems() in bus.py breaks Python3 support

### ISSUE THREAD

**Issue by jrpetrus** [potentialventures/cocotb#589]
https://github.com/potentialventures/cocotb/blob/f4332995430780bef4b3ae03a07673c3a1f39729/cocotb/bus.py#L88

./bus.py:88:        for attr_name, sig_name in _build_sig_attr_dict(signals).iteritems():
./bus.py:101:        for attr_name, sig_name in _build_sig_attr_dict(optional_signals).iteritems():
./bus.py:134:        for attr_name, hdl in self._signals.iteritems():
./bus.py:169:        for attr_name, hdl in self._signals.iteritems():

**Comment by imphil** [comment]
Fixed in https://github.com/potentialventures/cocotb/commit/5ad511f72e95b73b32a0bd784a5e14fcd47b3b76. Can be closed.

**Comment by jrpetrus** [comment]
No, `iteritems()` still appears twice.
