### ISSUE TITLE
Cocotb website frozen in version 0.4

### ISSUE THREAD

**Issue by Martoni** [potentialventures/cocotb#627]
Is it normal that cocotb website describe version 0.4 ?
http://potential.ventures/cocotb/

It's a really old revision no ?

**Comment by eric-wieser** [comment]
I think http://cocotb.readthedocs.io/en/latest/ might be up to date.

@stuarthodgson, can you set the (currently absent) url in the github UI to point to http://cocotb.readthedocs.io/en/latest/?

**Comment by eric-wieser** [comment]
I think the cocotb website comes from the `gh-pages` branch, which is similarly out of date

**Comment by Martoni** [comment]
The problem is that if we google/duckduckgo cocotb this obsolete link appear.

**Comment by stuarthodgson** [comment]
Mm, ok, not quite sure where that is even hosted. We will track it down.

**Comment by eric-wieser** [comment]
It's hosted by github, on the `gh-pages` branch.

**Comment by Martoni** [comment]
It could be a good idea to delete these gh-pages. Because with simple search we have the impression that cocotb is old unmaintained project. Which is false !

**Comment by stuarthodgson** [comment]
If I search for cocotb it points to the 1.0.0 pages so I'm now unsure what the problem even is here.

**Comment by eric-wieser** [comment]
Fourth link on google:

![image](https://user-images.githubusercontent.com/425260/48080778-5b26fa00-e1a3-11e8-8802-a61dab37a129.png)

Take it down with `git push -d origin gh-pages` (unless you want to back that branch up first

**Comment by eric-wieser** [comment]
Also, ping on [this comment](https://github.com/potentialventures/cocotb/issues/627#issuecomment-408726884)

**Comment by Martoni** [comment]
For me, duckduckgo is first link : 
![cocotbduckduckgo](https://user-images.githubusercontent.com/789580/48089173-1c755c00-e204-11e8-8cf8-ef0bfaa009a8.png)
