### ISSUE TITLE
BUG: gpi_set_signal_value_long ignores the top 32 bits on platforms where sizeof(long) != 4

### ISSUE THREAD

**Issue by eric-wieser** [potentialventures/cocotb#656]
All the current implementations of `GpiSignalObjHdl::set_signal_value(long)` end up casting to `uint32`, which loses bits on 64-bit non-windows.

Easy fix would be just to rename it to `gpi_set_signal_value_uint32`, and change the types of the parameters to `uint32`

**Comment by elgorwi** [comment]
Handle.py ensures that only values that fit within 32-bit and HDL signals up to 32-bit are driven using set_signal_val_long. 
Fair point about changing this to uint32 though.
 
On another note, perhaps another method using hex strings (eg. set_signal_val_hex) could be introduced to drive larger signals more efficiently than set_signal_val_str.

**Comment by stuarthodgson** [comment]
I don't think there is anything that needs fixing here, would just be code churn.
