### ISSUE TITLE
Multiple undocumented environment variables

### ISSUE THREAD

**Issue by cmarqu** [potentialventures/cocotb#676]
The environment variables ``COCOTB_LOG_LEVEL``, ``COCOTB_SCHEDULER_DEBUG``, ``COCOTB_ENABLE_PROFILING`` are undocumented.
(Discovered while reading through #376.)

**Comment by stuarthodgson** [comment]
And COCOTB_ATTACH

**Comment by cmarqu** [comment]
> And COCOTB_ATTACH, MEMCHECK

``COCOTB_ATTACH`` I have #671 and a pull request #672 for.

**Comment by stuarthodgson** [comment]
It's mentioned yeah but I think a central place that has them all that is referenced from other sections like your troubleshooting is the way forwards.

**Comment by cmarqu** [comment]
I just saw that Sphinx has a glossary feature that may fit nicely here: https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html?highlight=glossary#glossary

**Comment by cmarqu** [comment]
I tried the glossary feature and it works well. I'll send a pull request but would like to do that after #601 has been merged.

**Comment by s3bs** [comment]
Would it makes sense to prefix all of the environment variables with `COCOTB`. Especially `VERSION` has the potential to be very overloaded.

**Comment by cmarqu** [comment]
I agree; question is, how important is it for some variables to have a deprecation phase (``VERSION`` for instance can maybe just be renamed without disrupting any users' flow, ``MODULE`` needs a few releases before it can be removed).
