### ISSUE TITLE
Forked coro join() sometimes doesn't return returned value

### ISSUE THREAD

**Issue by Matthewar** [potentialventures/cocotb#748]
The following code:
```python
@cocotb.coroutine
def wait_for(clk, cycles):
  for _ in xrange(cycles):
    yield RisingEdge(clk)
  raise ReturnValue("It worked!")

@cocotb.coroutine
def show_problem(dut):
  cocotb.fork(Clock(dut.clk, 2000, 'ps').start())

  short_wait = cocotb.fork(wait_for(dut.clk, 10))
  long_wait = cocotb.fork(wait_for(dut.clk, 30))

  yield wait_for(dut.clk, 20)

  a = yield short_wait.join()
  b = yield long_wait.join()
  print "Results: "+repr(a)+" - "+repr(b)
```
Outputs: `Results: <cocotb.triggers.NullTrigger object at 0x7fffeacd3050> - 'It worked!'`

Which is inconsistent and confusing behavior, the ReturnValue is sometimes provided (if join is called before the method finishes) and sometimes not (if join is called afterward). We ought to be returning the returned value in each case.

It looks like there is a somewhat easy workaround for this: replace `x = yield foo.join()` with:
```python
yield foo.join()
x = foo.retval
```

**Comment by eric-wieser** [comment]
I think this might already be fixed in master as part of #723

**Comment by Matthewar** [comment]
Sure, probably worth making a test case for it.

**Comment by eric-wieser** [comment]
Actually, looks like I [already wrote that test](https://github.com/potentialventures/cocotb/pull/723/files#r241956719)

**Comment by Matthewar** [comment]
You're right, there's a test and the functionality already works, however I added an additional specific test case too.
