### ISSUE TITLE
Standard python exception handling and reporting

### ISSUE THREAD

**Issue by jeinstei** [potentialventures/cocotb#829]
I'm finding that python exceptions will fail a simulation with the message below, but not actually perform a traceback or report the exception.

`#     0.00ns ERROR    cocotb.scheduler                            __init__.py:190  in _sim_event                      Failing test at simulator request before test run completion: Simulator shutdown prematurely`

My call graph is: cocotb.test > yield cocotb.coroutine > setup_function

I've tried raising RuntimeError, StandardError, ValueError, and NotImplementedError, and TestError, and I get the same results.

**Comment by eric-wieser** [comment]
Can you paste the full stack trace? What version of cocotb?

**Comment by jeinstei** [comment]
This was actually related to a previous ticket that I close.d I somehow was registering objects multiple times which was breaking things. Let me close this one out and if I still see it will reopen with more information.

There was actually no stack trace, which was the entire problem in the first place. Things might have changed now though.
