### ISSUE TITLE
MSYS makefile issue

### ISSUE THREAD

**Issue by garmin-mjames** [potentialventures/cocotb#853]
I am seeing an issue in the MSYS makefiles relating to use of $(abspath ) function

This is generating broken paths such as:
```
make[1]: *** No rule to make target `/d/git/cocotb/tests/test_cases/test_plusargs/d:/git/cocotb/makefiles/../cocotb/share/makefiles/Makefile.sim'.  Stop.
```

Switching to $(realpath ) function cleans up the path and canonicalizes it, and everything works with the new packaging setup.

From the GNU make documentation:

> $(realpath names…)
> 
>     For each file name in names return the canonical absolute name. A canonical name does not contain any . or .. components, nor any repeated path separators (/) or symlinks. In case of a failure the empty string is returned. Consult the realpath(3) documentation for a list of possible failure causes.

Are there any objections to changing the makefiles to use realpath?

**Comment by imphil** [comment]
Please open a PR for it, sounds like a reasonable change.
