### ISSUE TITLE
Quick start instructions in `README.md` don't work

### ISSUE THREAD

**Issue by Harnesser** [potentialventures/cocotb#861]
Hi all,
I'm on linuxmint and tried to follow the instructions in the README, but things didn't work.

Getting:
```
make: cocotb-config: Command not found
Makefile:60: /Makefile.inc: No such file or directory
make: cocotb-config: Command not found
Makefile:61: /Makefile.sim: No such file or directory
make: *** No rule to make target '/Makefile.sim'.  Stop.
```

Do I have to install this as a Python package? Instructions in https://cocotb.readthedocs.io/en/latest/quickstart.html aren't too clear either.

**Comment by imphil** [comment]
cocotb just recently merged support for python packages, and that's not documented yet (#837). Youc an either use the 1.1 release version by checking out the `v1.1` tag in git, or install cocotb with pip using "pip install -e ." from the git checkout.

**Comment by Harnesser** [comment]
Gotcha - thanks for the reply!
