### ISSUE TITLE
List all Signals in Design

### ISSUE THREAD

**Issue by yrrapt** [potentialventures/cocotb#890]
Hi,

I'm trying to figure out a way to get a list of all the signal nodes in the design during a test.

This would be helpful because I'm designing for space application where radiation can cause random bit flips.  I want to be able to randomly select a signal in the design and flip a bit to determine how well the system responds.

Thanks in advance for any help you could provide.

**Comment by pwiecha** [comment]
https://github.com/lukedarnell/cocotb/blob/master/tests/test_cases/orconf2018/cocotb_orconf2018.pdf
Slide 33 may be helpful

**Comment by yrrapt** [comment]
That looks like what I need, thanks for the help.

**Comment by cmarqu** [comment]
@yrrapt Interesting - see https://github.com/potentialventures/cocotb/issues/657#issuecomment-436408411 too. If you come up with something that you can share (not necessarily code, also experiences), please let us know.
