### ISSUE TITLE
New User of Cocotb

### ISSUE THREAD

**Issue by morsingnet** [potentialventures/cocotb#902]
Hey Guys,
Im new to cocotb and wanted to try to the simple example, but I keep running into this issue:
```

$ git clone https://github.com/potentialventures/cocotb
Cloning into 'cocotb'...
$ cd cocotb/examples/endian_swapper/tests
$ make
make: cocotb-config: Command not found
Makefile:60: /Makefile.inc: No such file or directory
make: cocotb-config: Command not found
Makefile:61: /Makefile.sim: No such file or directory
make: *** No rule to make target '/Makefile.sim'.  Stop.
```

Anyone been there before?
Running on ubuntu 18.04

**Comment by tmeissner** [comment]
Maybe you have to do `pip install ./cocotb` first, after checking out without as mentioned here:  https://github.com/potentialventures/cocotb#quickstart There was some work to support cocotb as package, but it seems not documented on the readthedocs site.

**Comment by morsingnet** [comment]
Thanks @tmeissner, im moving into a bigger can-of-worms I think.

```
$ git clone https://github.com/potentialventures/cocotb
Cloning into 'cocotb'...
$ pip install ./cocotb
Processing ./cocotb
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named setuptools
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-3WdWd2-build/
```
Im running this on a minimal ubuntu 18.04. I might have to install more packages?

**Comment by morsingnet** [comment]
added 
`sudo apt-get install python-setuptools`
It works now :)
Thanks @tmeissner - im off to the testing land

**Comment by morsingnet** [comment]
BTW - the PIP install step is missing in this guide:

https://github.com/potentialventures/cocotb/blob/master/documentation/source/quickstart.rst#running-an-example

- Christian

**Comment by themperek** [comment]
https://github.com/potentialventures/cocotb/pull/881
