### ISSUE TITLE
Travis is failing on master

### ISSUE THREAD

**Issue by eric-wieser** [potentialventures/cocotb#928]
Seems to be caused by the merge of #917 in 8bf587f79672812f1d02ae6fa8f98d308345c96f, even though the travis run on that commit passed.

[Failing build](https://travis-ci.org/potentialventures/cocotb/builds/528430282), fails for:

* Py 2.7 + docker
* Py 3.5 + docker
* Py 2.7 + mac

but passes for:

* Py 3.7 + travis
* Py 3.6.7 + travis
* Py 3.7 + windows
* Py 3.6 + mac

A [passing build](https://travis-ci.org/potentialventures/cocotb/jobs/528430290) looks like:
```
     0.00ns CRITICAL cocotb.gpi                               close_module.v:64   in                                 This is a a fatal message that fails the test
     1.06ns ERROR    cocotb.scheduler                            __init__.py:182  in _sim_event                      Failing test at simulator request
 10000.00ns ERROR    cocotb.scheduler                            __init__.py:190  in _sim_event                      Failing test at simulator request before test run completion: Simulator shutdown prematurely
 10000.00ns INFO     cocotb.regression                         regression.py:288  in handle_result                   Test errored as expected: test_failure_from_system_task (result was SimFailure)
 10000.00ns INFO     cocotb.regression                         regression.py:209  in tear_down                       Passed 1 tests (0 skipped)
 10000.00ns INFO     cocotb.regression                         regression.py:373  in _log_test_summary   
```

A failing build looks like
```
     0.00ns ERROR    cocotb.gpi                               close_module.v:63   in                                 This is an error message
     0.00ns CRITICAL cocotb.gpi                               close_module.v:64   in                                 This is a a fatal message that fails the test
     1.06ns ERROR    cocotb.scheduler                            __init__.py:182  in _sim_event                      Failing test at simulator request
     1.06ns ERROR    cocotb.regression                         regression.py:298  in handle_result                   Test Failed: test_failure_from_system_task (result was TestFailure)
     1.06ns ERROR    cocotb.regression                         regression.py:206  in tear_down                       Failed 1 out of 1 tests (0 skipped)
```

**Comment by eric-wieser** [comment]
With some more investigation - the "failing" tests are due to:
```
TestFailure('Failure from external source: This is a a fatal message that fails the test',)
```
while the passing tests are due to
```
SimFailure('Failing test at simulator request before test run completion: Simulator shutdown prematurely')
```

So there are two things wrong here:
* The test is bad, and should be checking for `TestFailure` (`expect_failure=True`) not `SimFailure` (`expect_error=True`)
* `SimFailure` vs `TestFailure` seems to vary by platform / python version (!)

**Comment by imphil** [comment]
Thanks for looking into that @eric-wieser. I saw the failures and retriggered them before (as travis was having a really bad weekend with many tests sporadically failing for no good reason). But the current failures are sticking and we need to debug them before merging anything else.

I won't have time to look into that until tonight or tomorrow, so if you find anything please let me now (or create a PR).

**Comment by eric-wieser** [comment]
One option would be just to mark the test as skipped, and come back to it later.

I was able to make the error go away on a local branch, although I still have no understanding of what makes the jobs different.

**Comment by eric-wieser** [comment]
@imphil, can you restart https://travis-ci.org/potentialventures/cocotb/builds/528342843?

**Comment by eric-wieser** [comment]
@imphil: Also, can you create a `ci-temp` branch pointing at 63a06bf2b85e760bd2ea999555bb675861ef9a4d? travis won't let me bisect without one

**Comment by imphil** [comment]
> @imphil, can you restart / clone https://travis-ci.org/potentialventures/cocotb/builds/528342843?

done

> @imphil: Also, can you create a ci-temp branch pointing at 63a06bf? travis won't let me bisect without one

done as well.

**Comment by eric-wieser** [comment]
Thanks, updated #931, #932, and #933 to use `ci-temp` as the base - hopefully that will reveal which other commit made #917 go from passing to failing
