### ISSUE TITLE
GHDL can also use COMPILE_ARGS no ?

### ISSUE THREAD

**Issue by Martoni** [potentialventures/cocotb#994]
I saw in documentation that only VCS and Icarus can use COMPILE_ARGS. In cocotb/documentation/source/building.rst : 

>   ``COMPILE_ARGS``
>       Any arguments or flags to pass to the compile stage of the simulation. Only applies to simulators with a separate compilation stage (currently Icarus and VCS).

But it can also be used with GHDL has a saw in makefile.ghdl : 
```
# Compilation phase
analyse: $(VHDL_SOURCES) $(SIM_BUILD)
	cd $(SIM_BUILD) && \
	$(foreach SOURCES_VAR, $(filter VHDL_SOURCES_%, $(.VARIABLES)), \
		$(CMD) -a $(GHDL_ARGS) $(COMPILE_ARGS) --work=$(SOURCES_VAR:VHDL_SOURCES_%=%) $($(SOURCES_VAR)) && ) \
	$(CMD) -a $(GHDL_ARGS) $(COMPILE_ARGS) --work=$(RTL_LIBRARY) $(VHDL_SOURCES) && \
	$(CMD) -e $(GHDL_ARGS) $(COMPILE_ARGS) --work=$(RTL_LIBRARY) $(TOPLEVEL)

```

Maybe documentation should be updated no ?

**Comment by imphil** [comment]
Thanks for reporting this. I'd appreciate a pull request for this issue. (Please do a quick grep check what other backends support this argument.)

**Comment by Martoni** [comment]
Ok I'm doing it.

**Comment by Martoni** [comment]
Done in pull request #995
